### ISSUE TITLE
Multiple calls to getDistance() in the same comparison expression

### ISSUE THREAD

**Issue by platisd** [fabianfroding/group3car#1]
Consecutive calls to `getDistance()` is **NOT** guaranteed to return the same results. This, aside of needlessly slowing down your code, can introduce a nasty and very hard to detect bug. Remember: whenever you call `getDistance()` a completely *new* measurement is initiated! It could be (very) different from the previous one.

You are misusing this throughout your branches, for example [here](https://github.com/fabianfroding/group3car/blob/Bence/ParallelParking/ParallelParking.ino#L93). Please fix! :+1:

**Comment by niguelchaos** [comment]
So we should have something like 
frontdistance = sensor.getDistance();?
should we have all the other methods/ measurements be put in a variable as well? Like setAngle, setSpeed, etc?
Where should these variables be? should they be global, or inside the methods they are supposed to be used in?

**Comment by platisd** [comment]
> So we should have something like
frontdistance = sensor.getDistance();?

Yes, precisely! :+1: 
For the rest, no, not necessarily at least. Just keep in mind that whenever you do a `get` operation on a sensor then a *new* measurement is conducted. If you don't want to take a new measurement then don't  call `get` multiple times. :smiley_cat:

**Comment by fabianfroding** [comment]
That method is an old one, we are using getParkingSpotSize().
Since the car will be moving in order to measure the parking spot size, we need to use sensor.getDistance() several times to detect when a new obstacle appears etc.

**Comment by platisd** [comment]
[This](https://github.com/fabianfroding/group3car/blob/fabian/ParallelParking/ParallelParking.ino#L91) is wrong for the reasons explained above:

```cpp
  if(rightSound.getDistance() <= 10 && odometerRight.getDistance() > CAR_SIZE * 2 || rightSound.getDistance() == 0 && odometerRight.getDistance() > CAR_SIZE * 2) {
```

You should not call `rightSound.getDistance()` twice and neither `odometerRight.getDistance()` for that matter, as its value could also have changed.
